### ISSUE TITLE
Prepare to cease referring to AMO

### ISSUE THREAD

**Issue by grahamperrin** [RandomEngy/RehostImage#10]
The header paragraph at https://github.com/RandomEngy/RehostImage refers to 

- https://addons.mozilla.org/en-US/firefox/addon/rehost-image/

With listings for legacy extensions [scheduled to disappear in early October 2018](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/), you might like to remove the reference. 

The **Releases** tab here is prominent. 

If you'd like to quote a [Classic Add-ons Archive](https://github.com/JustOff/ca-archive/) URL: 

- caa:addon/rehost-image

**Comment by RandomEngy** [comment]
> caa:addon/rehost-image

Is that a URL? What is that?

**Comment by grahamperrin** [comment]
Yep, a Classic Add-ons Archive URL:

![2018-09-22 20 09 57 rehost image classic add-ons archive](https://user-images.githubusercontent.com/192271/45920944-88457480-bea3-11e8-9ce5-1197623b8d5a.png)

**Comment by RandomEngy** [comment]
Sure, why not? Made the change.
