### ISSUE TITLE
Imgur Rehosting Fails

### ISSUE THREAD

**Issue by NeurionSA** [RandomEngy/RehostImage#3]
As of today, attempts to rehost an image via Imgur will fail with the following message:

Upload failed.

400 Bad Request

{"data":{"error":{"code":1003,"message":"File type invalid","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

**Comment by RandomEngy** [comment]
I didn't change anything on my end. It could be an Imgur API issue. I've contacted Imgur support about it.

**Comment by Corruptinglyneedful** [comment]
Is there a way to swap what hosting site it's using in the mean time until Imgur fixes their shite API?

**Comment by danmun** [comment]
Yes. Go to about:addons and find RehostImage, then click Options, you can set your preferences there.

**Comment by mikhoul** [comment]
@RandomEngy  Do you have some News from IMGUR ? 

[Sharex](https://github.com/ShareX/ShareX) upload fine on IMGUR so maybe look at their code to see the difference from your code.

Regards :octocat:

**Comment by RandomEngy** [comment]
Looks like it's an issue with the paid API that I use, other people are running into this as well.

**Comment by RandomEngy** [comment]
![image](https://cloud.githubusercontent.com/assets/9450861/24072955/687dc5cc-0bac-11e7-8d05-5dc0459033f6.png)

Looks like they fixed it.
