### ISSUE TITLE
SFTP Support

### ISSUE THREAD

**Issue by McCovican** [RandomEngy/RehostImage#7]
Hi, it would be great if this could add in SFTP support. As it is, my host of choice has FTP/FTPS disabled entirely, and so trying to force port 22 with the FTP option just errors out.

Thanks!

**Comment by RandomEngy** [comment]
Thanks for the suggestion. I looked into SFTP, but I would need to implement a lot of it from scratch and I don't have time to do it.

**Comment by McCovican** [comment]
Fair enough. Thanks for answering.
